# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fba2e20be9d3cd1d101f15c3b25602c7b03401efcaecdb43df117e4391f846583b2aa35f8a74e181181de118450516a723581166fcf93a2da72f617e2392661d
  stripe_secret_key: 'sk_test_RtD0URFi6IkU7cdGsNms5TKj00lRyT23Gv'
  stripe_publishable_key: 'pk_test_m4Jw4iUOPrXCbAnWJf1Mi6FT00EJBmcRr0'


test:
  secret_key_base: 619ce15c3e8d000cf63c94795f8ed06917a5f62f3db3e111732fc12200c35b8b32c4d76b39a2e83b20b828cca6411cf7471d568c7496188906e58d6067bfb20e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
